version: '3'
services:
  web:
    image: sanketkulkarni/magento23-nginx
    ports:
      - "3000:80"
    external_links:
      - mysql:mysql
      - phpmyadmin:phpmyadmin 
    restart: always
    container_name: magento23docker_web
    depends_on:
      - mysql
    volumes:
      - ./public:/var/www
  phpfpm:
    image: sanketkulkarni/magento23-phpfpm
    ports:
      - "9000:9000"
    restart: always
    container_name: magento23docker_phpfpm
    volumes:
      - ./public:/var/www
    environment:
      M2SETUP_DB_HOST: mysql
      M2SETUP_DB_NAME: magento2
      M2SETUP_DB_USER: root
      M2SETUP_DB_PASSWORD: root
      M2SETUP_BASE_URL: http://localhost:3000/
      M2SETUP_BACKEND_FRONTNAME: admin
      M2SETUP_ADMIN_FIRSTNAME: Admin
      M2SETUP_ADMIN_LASTNAME: User
      M2SETUP_ADMIN_EMAIL: magento-admin@example.com
      M2SETUP_ADMIN_USER: admin
      M2SETUP_ADMIN_PASSWORD: admin123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
    - mysql
    ports:
      - 8186:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysql
      MYSQL_DATABASE: magento2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  redis:
    image: redis
    expose:
      - 6379
  rabbitmq:
    image: rabbitmq
    container_name: magento23docker_rabbitmq
    ports:
      - "5672:5672"
  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql
volumes:
  dbdata: